// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VClinic.Infrastructure.Persistence;

#nullable disable

namespace VClinic.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Medico", b =>
                {
                    b.Property<long>("IdMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdMedico"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<long>("IdPersona")
                        .HasColumnType("bigint");

                    b.Property<string>("NumeroColegiado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdMedico");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.HasIndex("NumeroColegiado")
                        .IsUnique();

                    b.ToTable("Medicos", (string)null);
                });

            modelBuilder.Entity("VClinic.Domain.Entities.CentroMedico", b =>
                {
                    b.Property<int>("IdCentroMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCentroMedico"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaFundacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rnc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdCentroMedico");

                    b.ToTable("CentrosMedicos", (string)null);
                });

            modelBuilder.Entity("VClinic.Domain.Entities.DatosPersona", b =>
                {
                    b.Property<long>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPersona"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTipoIdentificacion")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdPersona");

                    b.HasIndex("IdTipoIdentificacion", "NumeroIdentificacion")
                        .IsUnique();

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Empleado", b =>
                {
                    b.Property<long>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdEmpleado"));

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<int>("IdCargo")
                        .HasColumnType("int");

                    b.Property<long>("IdPersona")
                        .HasColumnType("bigint");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("CodigoEmpleado")
                        .IsUnique();

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Paciente", b =>
                {
                    b.Property<long>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPaciente"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<int>("IdGrupoSangre")
                        .HasColumnType("int");

                    b.Property<int>("IdHistorial")
                        .HasColumnType("int");

                    b.Property<long>("IdPersona")
                        .HasColumnType("bigint");

                    b.HasKey("IdPaciente");

                    b.HasIndex("IdHistorial")
                        .IsUnique();

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("Medico", b =>
                {
                    b.HasOne("VClinic.Domain.Entities.DatosPersona", "Persona")
                        .WithOne("Medico")
                        .HasForeignKey("Medico", "IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Empleado", b =>
                {
                    b.HasOne("VClinic.Domain.Entities.DatosPersona", "Persona")
                        .WithOne("Empleado")
                        .HasForeignKey("VClinic.Domain.Entities.Empleado", "IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("VClinic.Domain.Entities.DatosPersona", "Persona")
                        .WithOne("Paciente")
                        .HasForeignKey("VClinic.Domain.Entities.Paciente", "IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("VClinic.Domain.Entities.DatosPersona", b =>
                {
                    b.Navigation("Empleado");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
